name: TICS scan

on:
  schedule:
    - cron: '00 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
    TICS:
      runs-on: [self-hosted, linux, amd64, tiobe]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install -y tox libvirt-dev
            sudo snap install astral-uv --channel latest/stable --classic

        - name: Run coverage tests
          run: tox -e unit

        - name: Install hypervisor snap dependencies
          run: |
            uv sync
            source .venv/bin/activate

        - name: TICS
          uses: tiobe/tics-github-action@v3
          with:
            mode: qserver
            viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
            ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
            project: snap-openstack-hypervisor
            branchdir: ${{ env.GITHUB_WORKSPACE }}
            installTics: true
